### ISSUE TITLE
TypeError when trying to use UK marketplace

### ISSUE THREAD

**Issue by Teleshot** [tivac/black-friday#1]
Hi, I am trying to use this for the Amazon UK marketplace but I am getting a TypeError. If I try to use this for US Amazon marketplace (default) it works fine.

Amazon US:

```
$ node . --customer=A1RSS32******** --session=191-4629327-******** 1c4798bc
Deals:
1c4798bc : Anker® Astro Slim3 6000mAh Ultra-Slim 2-Port External Battery

Going to work...
1c4798bc : Anker® Astro Slim3 6000mAh Ultra-Slim 2-Port External Battery
  Waiting 60886s to add
```

Amazon UK: Error with '--marketplace' argument 

```
$ node . --marketplace=A3P5ROKL5A1OLE --customer=A1RSS3******** --session=279-7263498-******* 40b14390
Deals:

TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Request._callback (c:\Development\black-friday\index.js:112:16)
    at Request.self.callback (c:\Development\black-friday\node_modules\request\request.js:129:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (c:\Development\black-friday\node_modules\request\request.js:873:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (c:\Development\black-friday\node_modules\request\request.js:824:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

Is there something I am doing wrong? 

Thank you for your help.

**Comment by tivac** [comment]
@Teleshot Sorry, no idea! I haven't touched this since I originally built it in a hurry for a friend a year ago.

I'll see if I can find some time to poke around, but I can't promise anything.

**Comment by tivac** [comment]
Never found that time, sorry!
